name: stock-news-tracker
channels:
  - defaults
dependencies:
  - aiohttp=3.7.3
  - astroid=2.4.2
  - async-timeout=3.0.1
  - atomicwrites=1.4.0
  - attrs=20.3.0
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2021.1.19
  - cachetools=4.2.1
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=3.0.4
  - colorama=0.4.4
  - cryptography=3.3.1
  - google-api-core=1.22.2
  - google-auth=1.24.0
  - google-cloud-core=1.5.0
  - google-cloud-storage=1.35.0
  - google-crc32c=1.1.2
  - google-resumable-media=1.2.0
  - googleapis-common-protos=1.52.0
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - iniconfig=1.1.1
  - intel-openmp=2020.2
  - isort=5.6.4
  - jsonlines=2.0.0
  - lazy-object-proxy=1.4.3
  - libcrc32c=1.1.1
  - libprotobuf=3.14.0
  - mccabe=0.6.1
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - more-itertools=8.6.0
  - multidict=4.7.6
  - numpy=1.19.2
  - numpy-base=1.19.2
  - openssl=1.1.1i
  - packaging=20.9
  - pandas=1.2.1
  - pip=20.3.3
  - pluggy=0.13.1
  - protobuf=3.14.0
  - py=1.10.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pylint=2.6.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pysocks=1.7.1
  - pytest=6.2.2
  - python=3.7.9
  - python-dateutil=2.8.1
  - pytz=2020.5
  - requests=2.25.1
  - rsa=4.7
  - selenium=3.141.0
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.33.0
  - toml=0.10.1
  - typed-ast=1.4.2
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.26.3
  - wheel=0.36.2
  - wrapt=1.11.2
  - yarl=1.5.1
  - zipp=3.4.0
  - zlib=1.2.11

